# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
# Ubuntu Desktop 20.04
  config.ssh.insert_key = false
 # config.vbguest.auto_update = true
  config.vm.define :server do |cn|
    cn.vm.box = "jcpetro97/centos8"
    cn.vm.synced_folder '.', '/vagrant', disabled: false
    cn.vm.hostname = "ansibledev"
    cn.vm.network "private_network", ip: "192.168.76.2"
    cn.vm.provider "virtualbox" do |tl2d|
      tl2d.memory = 2048
      tl2d.cpus = 2
      tl2d.gui = false
      tl2d.name = "centos8-ansiblecn"
    end
    cn.vm.provision "shell" do |s|
      s.path = "../shared/rhel.sh"
      s.env   = {ANSIBLE_VERSION:ENV['ANSIBLE_VERSION']}
    end
  end
  config.vm.define :ubuntu2004 do |ubuntu2004|
    ubuntu2004.vm.box = "jcpetro97/ubuntu2004"
    ubuntu2004.vm.hostname = "ubuntu2004"
    ubuntu2004.vm.network "private_network", ip: "192.168.76.3"
    ubuntu2004.vm.provider "virtualbox" do |cl1|
      cl1.memory = 1024
      cl1.cpus = 1
      cl1.gui = false
      cl1.name = "ubuntu2004-client1"
    end
  end
  config.vm.define :centos7 do |centos7|
    centos7.vm.box = "jcpetro97/centos7"
    centos7.vm.hostname = "centos7"
    centos7.vm.network "private_network", ip: "192.168.76.4"
    centos7.vm.provider "virtualbox" do |cl2|
      cl2.memory = 1024
      cl2.cpus = 1
      cl2.gui = false
      cl2.name = "centos7-client2"
    end
  end
  config.vm.define :centos8 do |centos8|
    centos8.vm.box = "jcpetro97/centos8"
    centos8.vm.hostname = "centos8"
    centos8.vm.network "private_network", ip: "192.168.76.5"
    centos8.vm.provider "virtualbox" do |cl3|
      cl3.memory = 1024
      cl3.cpus = 1
      cl3.gui = false
      cl3.name = "centos8-client3"
    end
  end

# Add more client definitions here

end
