# -*- mode: ruby -*-
# vi: set ft=ruby :

CENTOS8_IMAGE = "jcpetro97/centos8"
SUBNET = "192.168.6"
Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
    
  # centos8 control node
  config.vm.define :"centos8-controlnode" do |c8cn|
    c8cn.vm.box = CENTOS8_IMAGE
    c8cn.vm.hostname = "centos8-controlnode"
    c8cn.vm.network "private_network", ip: "#{SUBNET}.4"
    c8cn.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
      vb.gui = false
    end #vb
    c8cn.vm.synced_folder '.', '/vagrant', disabled: false
    c8cn.vm.provision :hosts, :sync_hosts => true
    c8cn.vm.provision "shell" do |s|
      s.inline = $centinstall
      s.env   = {ANSIBLE_VERSION:ENV['ANSIBLE_VERSION']}
    end # s
  end # c8cn
  
  # centos8 nodes
  (1..2).each do |i|     
    config.vm.define "centos8-node#{i}" do |centos8|
        centos8.vm.box = CENTOS8_IMAGE
        centos8.vm.hostname = "centos8-node#{i}"       
        centos8.vm.network :private_network, ip: "#{SUBNET}.#{i + 30}"     
        centos8.vm.provision :hosts, :sync_hosts => true
    end # end centos8 node
  end # end each loop
end # config

$centinstall = <<CENTSCRIPT
  #!/bin/bash
  # Install Python.
  /usr/bin/echo "------> installing python3 <------"
  /usr/bin/yum -y install python3 python3-pip sshpass
  /usr/bin/echo "------> upgrade pip <------"
  /usr/bin/python3 -m pip install --upgrade pip
  /usr/bin/echo "------> upgrade setuptools <------"
  /usr/bin/python3 -m pip install --upgrade setuptools
  # Install Ansible.
  if [ -z "${ANSIBLE_VERSION}" ];

    then
        /bin/echo "------> Install Latest Version of Ansible  <------"
        /usr/bin/python3 -m pip install ansible
    elif [[ $ANSIBLE_VERSION =~ "2.10" ]]
    then
        /bin/echo "------> Install Ansible $ANSIBLE_VERSION <------"
        /usr/bin/python3 -m pip install ansible-base==$ANSIBLE_VERSION
    else
        /bin/echo "------> Install Ansible $ANSIBLE_VERSION <------"
        /usr/bin/python3 -m pip install ansible==$ANSIBLE_VERSION
    fi

  #

  /usr/bin/echo "------> Verify Ansible Version <------"
  /usr/local/bin/ansible --version
CENTSCRIPT