# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
# Ubuntu Desktop 20.04
  config.vm.define :ansible do |ansible|
    ansible.vm.box = "geerlingguy/ubuntu2004"
    ansible.vm.hostname = "ansibledev"
    ansible.vm.network "private_network", ip: "192.168.64.2"
    ansible.vm.provider "virtualbox" do |tl2d|
      tl2d.memory = 2048
      tl2d.cpus = 2
      tl2d.gui = false
      tl2d.name = "ansibledev"
    end
  end
  config.vm.define :client1 do |client1|
    client1.vm.box = "geerlingguy/ubuntu2004"
    client1.vm.hostname = "Client1"
    client1.vm.network "private_network", ip: "192.168.64.3"
    client1.vm.provider "virtualbox" do |cl1|
      cl1.memory = 1024
      cl1.cpus = 1
      cl1.gui = false
      cl1.name = "Client1"
    end
  end
  config.vm.define :client2 do |client2|
    client2.vm.box = "geerlingguy/ubuntu2004"
    client2.vm.hostname = "client2"
    client2.vm.network "private_network", ip: "192.168.64.4"
    client2.vm.provider "virtualbox" do |cl2|
      cl2.memory = 1024
      cl2.cpus = 1
      cl2.gui = false
      cl2.name = "client2"
    end
  end

end
