# -*- mode: ruby -*-
# vi: set ft=ruby :

UBUNTU_IMAGE = "jcpetro97/ubuntu2004"
SUBNET = "192.168.4"
Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  
  # ubuntu control node
  config.vm.define :"ubuntu-controlnode" do |ubcn|
    ubcn.vm.box = UBUNTU_IMAGE
    ubcn.vm.hostname = "ubuntu-controlnode"
    ubcn.vm.network "private_network", ip: "#{SUBNET}.2"
    ubcn.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
      vb.gui = false
    end #vb
    ubcn.vm.synced_folder '.', '/vagrant', mount_options: ["dmode=755,fmode=755"],disabled: false
    ubcn.vm.provision :hosts, :sync_hosts => true
    ubcn.vm.provision "shell" do |s|
      s.inline = $ubinstall
      s.env   = {ANSIBLE_VERSION:ENV['ANSIBLE_VERSION']}
    end # s
  end # ubcn
    
  # ubuntu nodes
  (1..2).each do |i|     
    config.vm.define "ubuntu-node#{i}" do |ubuntu|
        ubuntu.vm.box = UBUNTU_IMAGE 
        ubuntu.vm.hostname = "ubuntu-node#{i}"       
        ubuntu.vm.network :private_network, ip: "#{SUBNET}.#{i + 10}"
        ubuntu.vm.provision :hosts, :sync_hosts => true
    end # end ubuntu
  end  # end each loop

end # config
$ubinstall = <<UBSCRIPT
  #!/bin/bash
  ANSIBLE_VERSION=${ANSIBLE_VERSION:-2.9.22}

  # Install Python.
  /bin/echo "------> installing python3 <------"
  /usr/bin/apt update
  /usr/bin/apt -y install python3 python3-pip sshpass
  /bin/echo "------> upgrade pip <------"
  /usr/bin/python3 -m pip install --upgrade pip
  /bin/echo "------> upgrade setuptools <------"
  /usr/bin/python3 -m pip install --upgrade setuptools
  # # Install Ansible.
  if [[ $ANSIBLE_VERSION =~ "2.9" ]]
  then
      /bin/echo "------> Install Ansible $ANSIBLE_VERSION <------"
      /usr/bin/python3 -m pip install ansible==$ANSIBLE_VERSION

  else
      /bin/echo "------> Install Ansible $ANSIBLE_VERSION <------"
      /usr/bin/python3 -m pip install ansible-base==$ANSIBLE_VERSION

  fi
  #
  /bin/echo "------> Verify Ansible Version <------"
  /usr/local/bin/ansible --version
UBSCRIPT
