---
- hosts: all
  become: true
  gather_facts: yes
  pre_tasks:
    - name: Copy Vagrant pub key to /etc/sshkeys.local
      ansible.builtin.copy:
        src: /vagrant/files/vagrant.pub
        dest: /etc/sshkeys.local/
        mode: 0644
        directory_mode: 0755
  roles:
    - role: UserManage
      vars:
        users_groups:
          - name: ansibletest
            gid: 672
            state: present
        users:
          - name: ansibletest
            comment: Ansible User
            uid: 672
            group: ansibletest
            append: "no"
            sudo: yes
            update_password: on_create
            state: present
    - role: sshd  
