---
- hosts: all
  become: true
  gather_facts: yes

  tasks:
    - name: "setup sshd to use /etc/sshkeys.local"
      block:
        - name: RedHat - check if /etc/ssh/sshd_config.d exists
          ansible.builtin.stat:
            path: /etc/ssh/sshd_config.d
          register: sshdconfigd_dir

        - name: RedHat - Configure sshd
          ansible.builtin.lineinfile:
            path: "/etc/ssh/sshd_config"
            regex: "^(#)?{{item.key}}"
            line: "{{item.key}} {{item.value}}"
            state: present
          loop:
            - { key: "AuthorizedKeysFile", value: "/etc/sshkeys/%u.pub /etc/sshkeys.local/%u.pub" }
            - { key: "PermitRootLogin", value: "no" }
            - { key: "PasswordAuthentication", value: "no" }
            - { key: "ChallengeResponseAuthentication", value: "no" }
            - { key: "GSSAPIAuthentication", value: "no" }
          register: sshd_legacy_config
          when: ansible_distribution_major_version == "7" or ansible_distribution_major_version == "8"

        - name: RedHat - Restart sshd
          ansible.builtin.systemd:
            name: sshd
            state: restarted
          when: sshd_legacy_config is changed

        - name: RedHat - Add pubkey and no password in /etc/ssh/sshd_config.d/02-pubkeys.conf
          ansible.builtin.copy:
            src: files/pubkeys.conf
            dest: /etc/ssh/sshd_config.d/02-pubkeys.conf
            owner: root
            group: root
            mode: 0444
          register: sshd_pubkey
          when: (sshdconfigd_dir.stat.exists) and (ansible_distribution_major_version >= "9")

        - name: RedHat - Restart sshd
          ansible.builtin.systemd:
            name: sshd
            state: restarted
          when: sshd_pubkey is changed
      when: ansible_os_family = "RedHat"